In [ ]:
import numpy as np

In [ ]:
a = np.array([3,5,8,6])

In [ ]:
a

array([3, 5, 8, 6])

In [ ]:
b = np.full_like(a,4)
print(b)

[4 4 4 4]


In [ ]:
np.zeros((5,), dtype=int)

array([0, 0, 0, 0, 0])

Initialize np array with 5 and make a vector of shape 4

In [ ]:
f = np.full(10,)
print (f)

[5 5 5 5 5 5 5 5 5 5]


In [ ]:
f.shape

(10,)

In [ ]:
f.dtype

dtype('int64')

In [ ]:
d = np.zeros((3, 5))
print (d)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
d.shape

(3, 5)

In [ ]:
s = (2,2)
np.zeros(s)

array([[0., 0.],
       [0., 0.]])

In [ ]:
a = np.array([2,4,6])
a*2

array([ 4,  8, 12])

In [ ]:
b = np.array([1,1,1])
a+b

array([3, 5, 7])

In [ ]:
a*b

array([2, 4, 6])

In [ ]:
c = np.array([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [ ]:
c.shape

(2, 3)

In [ ]:
c.ndim

2

In [ ]:
c.dtype

dtype('int64')

In [ ]:
c.itemsize

8

In [ ]:
c.nbytes

48

Note that the indexes start form 0

In [ ]:
c[1,2]

6

In [ ]:
c[1,-2]

5

In [ ]:
c[0,0]

1

In [ ]:
c[1, :]

array([4, 5, 6])

In [ ]:
c[:,2]

array([3, 6])

Task: Please initialize an array with 80,90,100 and find out what datatype would take the least and the most amount of bytes?

In [ ]:
test = np.array([100,300,500])
test.nbytes

24

In [ ]:
test = np.array([100,300,500], dtype='int32')
test.nbytes

12